### PR TITLE
[15.0][MIG] helpdesk_mgmt (14.0->15.0)

### PR DESCRIPTION
**Pull request by jacob88**

### CODE REVIEW

**Comment by gdgellatly** [comment]
Hi, as a minimum, if we agree that #281 is correct, then it should be part of standard migration. I'm not really familiar with the particular change to onchange domains.

**Comment by jacob88** [comment]
@gdgellatly I'm happy to bring the commits across, but I am also not familiar with that particular change to base Odoo.
I'll have a look at the code and verify that a deprecation warning is raised, if it is then we might as well make the change now to minimise any breaking changes later on.

**Comment by pedrobaeza** [comment]
Please cherry-pick f8ba1d9 (before the migration commit).

**Comment by jacob88** [comment]
@pedrobaeza Sorry I've been quite busy the last couple of weeks.

I have brought the latest commits across from 14.0 now.

**Review by pedrobaeza — APPROVED** [review]

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Pull request merged**
