### PR TITLE
[16.0] [ADD] helpdesk_mgmt_portal_follower: New module

### PR DESCRIPTION
**Pull request by BernatObrador**
Portal Follower
======================

This module adds the posibilty to add followers to a helpdesk ticket from the helpdesk form at the website portal.

Usage
=====

To make it work you just need to add the emails of the wanted followers to the Add Followers input splitted by comas.

cc https://github.com/APSL 158607

@miquelalzanillas @lbarry-apsl @peluko00 @javierobcn please review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please don't use plurals in module names

**Review by peluko00 — APPROVED** [review]
LGTM

**Review by lbarry-apsl — APPROVED** [review]
Reviewed. LGTM

**Review by miquelalzanillas — APPROVED** [review]
LGTM.

@pedrobaeza Do you think we can push this?

**Comment by pedrobaeza** [comment]
Shouldn't this be better called `helpdesk_mgmt_portal_follower` for better comprehension of the scope? About the feature itself, do you consider safe to allow to add any possible mail to the submitters? I see spam or privacy problems. Also, the term follower for us is well understood, but outside, users (and more through a portal) don't know about it. Maybe you can put the label as "Emails in copy" or similar.

**Comment by miquelalzanillas** [comment]
Hi @pedrobaeza ,

I'm agree with module name and field labeling. About the security, do you have any idea about how we can improve it?  I'm thinking about to add a restriction to only permit new follower adresses where the email domain mathces with the one of the partner assigned to the ticket, but in case of non business domains (gmail, hotmail, outlook, ...) will not have any sense.

**Comment by pedrobaeza** [comment]
Yeah, indeed it's a rabbit hole. You can put the warning in the ROADMAP and warn your potential users about that, and see how it progresses.

**Comment by miquelalzanillas** [comment]
Ok, thanks Pedro.

@BernatObrador could you check Pedro's suggestions?

**Comment by BernatObrador** [comment]
Hi @miquelalzanillas and @pedrobaeza! The name changes and the roadmap have been updated. Thanks so much for your contributions, @pedrobaeza!

**Comment by pedrobaeza** [comment]
You're welcome. Merging due to existing reviews:

/ocabot merge nobump

**Pull request merged**
