### PR TITLE
parameter `values` for `check` method may be None and when it is, it …

### PR DESCRIPTION
**Pull request by digitalsatori**
…will crash

### CODE REVIEW

**Comment by dalonsod** [comment]
@digitalsatori please check flake error at https://travis-ci.com/github/OCA/helpdesk/jobs/469740997#L317

**Review by dalonsod — APPROVED** [review]
Code review 👍

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by eLBati — APPROVED** [review]
LGTM

**Pull request merged**
