### PR TITLE
[16.0][IMP]helpdesk_mgmt: Improve UI/UX

### PR DESCRIPTION
**Pull request by moitabenfdz**
Delete "New Ticket" button from /my
Change position of "New Ticket" button in /my/tickets

This is a new approach of #452

### CODE REVIEW

**Review by flotho — APPROVED** [review]
functionnal test ok, 
code review OK,
LGTM

**Review by rvalyi — COMMENTED** [review]
much better!

**Review by tarteo — APPROVED** [review]
Thanks! Much better like this.
If you can improve the form also that would be really much appreciated.

image

Either way lets merge this. @OCA/helpdesk-maintainers

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The "New ticket" button in /my should be configurable, but you can't rip-off an existing option that will damage those that use it.

**Pull request closed without merging**
