### PR TITLE
[14.0][MIG] helpdesk_type

### PR DESCRIPTION
**Pull request by dalonsod**
Supersedes #189 due to inactivity. Includes #209 improvements already not included in v13

### CODE REVIEW

**Comment by dalonsod** [comment]
@ChristianSantamaria @marcelsavegnago could you review? Thanks!

**Review by etobella — APPROVED** [review]
Standard migration. Thanks for the demo data!!!

**Review by antoniocanovas — APPROVED** [review]
Functional review ok

**Review by ChristianSantamaria — APPROVED** [review]
LGTM

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by dalonsod** [comment]
Rebase made due to #237 , nothing changed in the addon

**Review by marcelsavegnago — APPROVED** [review]

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers could you merge this PR? Thanks!

**Comment by AntoniRomera** [comment]
@pedrobaeza @DarioLodeiros could you merge this PR #232 #236 ? Thanks!

**Pull request merged**
