### PR TITLE
[12.0] helpdesk_mgmt: improve ticket display name and name search, with ticket number

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by dalonsod** [comment]
@eLBati please take a look at #208 . At least, search part is solved...

**Review by mrcast — APPROVED** [review]
Functional test ok!

**Comment by dalonsod** [comment]
@eLBati would you resume this PR?

**Comment by eLBati** [comment]
@dalonsod what do you mean? It needs review , AFAIK

**Comment by dalonsod** [comment]
Codecov is not passed, is it possible to increase test coverage?

**Comment by eLBati** [comment]
AFAIK it would not be required for a beta module

**Comment by eLBati** [comment]
@dalonsod what do you think?

**Comment by dalonsod** [comment]
> 
> 
> @dalonsod what do you think?

I think I've found an error. I've made a PR, please check eLBati/helpdesk#1 
Added also test in order to check it and pass covecod for this PR

**Comment by eLBati** [comment]
:green_circle:

**Review by dalonsod — APPROVED** [review]
👍

**Review by marcelsavegnago — APPROVED** [review]

**Review by HekkiMelody — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please fw-port it to upper versions?

**Pull request merged**
