### PR TITLE
12.0

### PR DESCRIPTION
**Pull request by devCbssolutionsRo**
This is my first commit to OCA, hope I didn't broke any rule.
I made also some small addings to initial v11 module (security, and a team in category to send them automatically a email at creating of a new ticket).

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is the history brought with the method from https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0?

**Comment by devCbssolutionsRo** [comment]
:( no, but is simply a new branch from 11.0 with modificatios for 12.0

**Comment by pedrobaeza** [comment]
Please try this method instead.

**Comment by emagdalenaC2i** [comment]
@devCbssolutionsRo there is another PR for the migration to 12.0 in #25 

I will work in that PR this weekend

**Comment by pedrobaeza** [comment]
Superseeded by #37

**Pull request closed without merging**
