### PR TITLE
[IMP] Improved Data Output in Team tree view

### PR DESCRIPTION
**Pull request by GorkaMagra**
Improved overall data output in both the tree views of helpdesk.team, added team category tags, and the count of all the tickets assigned to that team.

### CODE REVIEW

**Review by emagdalenaC2i — APPROVED** [review]
LGTM Tested in runbot

**Review by JorgeQuinteros — APPROVED** [review]
Technical review

**Review by pedrobaeza — DISMISSED** [review]
Unless you improve the performance of the computed non-stored fields (through `read_group` for example), this is going to be killing the performance showing the tree.

Check one example for this kind of optimization in 

https://github.com/OCA/contract/blob/17c19ada32cc6625305a71a80cc6dfe88d95227e/contract/models/res_partner.py#L24-L39

**Comment by dalonsod** [comment]
@GorkaMagra would you resume this PR?

As @pedrobaeza said, you could change `_compute_todo_tickets()` method, maybe this code should work:
```
    def _compute_todo_tickets(self):
        ticket_model = self.env["helpdesk.ticket"]
        fetch_data = ticket_model.read_group(
            [("team_id", "in", self.ids)],
            ["team_id", "user_id", "unattended", "priority"],
            ["team_id", "user_id", "unattended", "priority"],
            lazy=False,
        )
        result = [
            [
                data["team_id"][0],
                data["user_id"] and data["user_id"][0],
                data["unattended"],
                data["priority"],
                data["__count"]
            ] for data in fetch_data
        ]
        for team in self:
            team.todo_ticket_count = sum([
                r[4] for r in result
                if r[0] == team.id
            ])
            team.todo_ticket_count_unassigned = sum([
                r[4] for r in result
                if r[0] == team.id and not r[1]
            ])
            team.todo_ticket_count_unattended = sum([
                r[4] for r in result
                if r[0] == team.id and r[2]
            ])
            team.todo_ticket_count_high_priority = sum([
                r[4] for r in result
                if r[0] == team.id and r[3] == "3"
            ])
```
The code above should only work if `unattended` field of `helpdesk.ticket` model becomes stored.

Could you check?

**Comment by dalonsod** [comment]
@GorkaMagra would you resume this PR?

**Comment by GorkaMagra** [comment]
> @GorkaMagra would you resume this PR?

Thanks ! And sorry, I've been quite busy this days, tried your code, seems to work fine ! Changes already pushed.

**Comment by GorkaMagra** [comment]
setUpClass in test_helpdesk_ticket_team was creating two tickets, few lines later, it was testing with an assertEqual that only 1 ticket was assigned to the team, therefore, it was failing. 2 != 1

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
