### PR TITLE
[FIX][14.0] helpdesk_mgmt: rename fr_FR.po to fr.po to allow its load…

### PR DESCRIPTION
**Pull request by mourad-ehm**
… & add translation

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please remove `[14.0]` from the commit message.

**Comment by mourad-ehm** [comment]
@pedrobaeza, Thanks for the review. I did it.

**Review by pedrobaeza — APPROVED** [review]
Another thing may be to label this as `[I18N]` according guidelines, but no more nitpickings. Let's fix it:

/ocabot merge patch

**Comment by ypapouin** [comment]
???, you don't made it correctly, the `fr` code is for french, the `fr_FR` is for french (France) (the po header is now wrong).
Adding `fr` should have been made directly from weblate.

image

**Pull request merged**
