### PR TITLE
[14.0][FIX] helpdesk_mgmt_timesheet allow_timesheet accessible from all user

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by kenayagi — APPROVED** [review]
👌

**Review by dalonsod — APPROVED** [review]
LGTM, only a cosmetic change, please fix typo in commit & PR titles (missing colon, move `[FIX] helpdesk_mgmt_timesheet allow_timesheet...` to `[FIX] helpdesk_mgmt_timesheet: allow_timesheet...`

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Comment by dalonsod** [comment]
@sergiocorato could you port it to v15/v16? Thanks!

**Comment by sergiocorato** [comment]
> @sergiocorato could you port it to v15/v16? Thanks!

Done! #629 and #630

**Pull request merged**
