### PR TITLE
[12.0] FIX helpdesk_mgmt: 403 error when user is follower of a ticket but can't access to partner_id

### PR DESCRIPTION
**Pull request by eLBati**
Following the same approach as https://github.com/odoo/odoo/blob/272602193f5647f7f2270ed6ec68777625a139dd/addons/sale/controllers/portal.py#L133

### CODE REVIEW

**Review by JorgeQuinteros — APPROVED** [review]
LGTM! Functional & Technical Review.

**Comment by Tisho99** [comment]
LGTM! Technical Review.

**Review by Tisho99 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by eLBati** [comment]
By memory:

 - Create 2 partners, A and B
 - Create a ticket for partner A
 - Assign partner B as follower of the ticket
 - Give portal access to partner B
 - Login as partner B

Partner B can see the ticket in their ticket list but gets 403 when opening the ticket

**Comment by pedrobaeza** [comment]
That should be reproducible on a test for avoiding future regressions. If not, we are adding patch over patch and not being sure the side effects of them.

**Comment by JorgeQuinteros** [comment]
Hello Pedro,
It can be replicated in the runbot, in short, if the portal user is a follower of a task for which he is not the partner_id, the 403 error is thrown.
According to the registration rules, a ticket follower should be able to see a ticket that they are a follower of. https://github.com/OCA/helpdesk/commit/6dd363d7ba6205c3d77e02f9bfe687ae1a1bd7d5

Following the same logic that is done to show the Sale Order records from the portal, sudo should be added, as here:
https://github.com/odoo/odoo/blob/272602193f5647f7f2270ed6ec68777625a139dd/addons/sale/controllers/portal.py#L133

what do you think?

**Comment by pedrobaeza** [comment]
Please add a test then for reproducing the problem and avoid future regressions. It can be a tour or a backend test with a portal user.

**Pull request closed without merging**
