### PR TITLE
[13.0][fix] Rules on who can access to tickets from the Portal should only be governed by the ir.rules.

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Fixes https://github.com/OCA/helpdesk/issues/213

@mileo @LoisRForgeFlow @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by mileo — APPROVED** [review]
Lgtm, could you backport it to 12 ? If not I can do it.

**Comment by LoisRForgeFlow** [comment]
I just applied pre-commit and pushed again.

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@mileo we'll do the backport.

**Comment by JordiBForgeFlow** [comment]
@MateuGForgeFlow can you apply this PR to v12?

**Pull request merged**
