### PR TITLE
[12.0] [MIG] helpdesk_mgmt

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You shouldn't put 30 commits in the PR. Please rebase your branch properly instead of doing a merge operation.

**Comment by pedrobaeza** [comment]
What is this?

**Comment by emagdalenaC2i** [comment]
Sorry, I was on a trip for a few days. I'll review it soon

**Comment by pedrobaeza** [comment]
@emagdalenaC2i can we close this in favor of #37?

**Pull request closed without merging**
