### PR TITLE
TESTING BUILD DO NOT MERGE ME

### PR DESCRIPTION
**Pull request by simahawk**
verify if it fails like here https://travis-ci.com/github/OCA/helpdesk/jobs/505440396
Origin: https://github.com/OCA/helpdesk/pull/227

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul seems we have a flappy issue w/ POT generation. See the error above. 
I got another similar error [here](https://travis-ci.com/github/OCA/product-attribute/jobs/508142936#L2487-L2487)
```
2021-05-26 11:43:57,164 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/data_dir/addons/14.0 

2021-05-26 11:43:57,165 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/addons 

2021-05-26 11:43:57,783 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/odoo/osv 

2021-05-26 11:43:57,784 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/odoo/report 

2021-05-26 11:43:57,784 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/odoo/modules 

2021-05-26 11:43:57,787 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/odoo/service 

2021-05-26 11:43:57,790 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/odoo/tools 

2021-05-26 11:43:57,799 6557 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /home/travis/odoo-14.0/odoo 

./product_seasonality/i18n/fr.po:181: duplicate message definition...

./product_seasonality/i18n/fr.po:171: ...this is the location of the first definition

msgmerge: found 1 fatal error

2021-05-26 11:43:57,816 6557 INFO openerp_test odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'sslmode=prefer dbname=openerp_test' 

2021-05-26 11:43:57,816 6557 ERROR openerp_test click_odoo.env_options: exception 

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click_odoo/env_options.py", line 214, in _invoke

    return self.org_invoke(ctx)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 1404, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 763, in invoke

    return __callback(*args, **kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click_odoo_contrib/makepot.py", line 165, in main

    purge_old_translations,

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click_odoo_contrib/makepot.py", line 88, in export_pot

    raise click.ClickException("%d invalid .po file(s) found" % invalid_po)

click.exceptions.ClickException: 1 invalid .po file(s) found

Error: 1 invalid .po file(s) found
```

**Comment by sbidoul** [comment]
@simahawk the relevant part seems to be this, which makes msgmerge fail:

```
./product_seasonality/i18n/fr.po:181: duplicate message definition...
./product_seasonality/i18n/fr.po:171: ...this is the location of the first definition
msgmerge: found 1 fatal error
```

So I'd say the duplicate must be fixed manually first.

**Comment by simahawk** [comment]
then it seems a different issue than https://travis-ci.com/github/OCA/helpdesk/jobs/505440396
bah, let's see if it works after rebase

**Comment by simahawk** [comment]
still failing [here](https://travis-ci.com/github/OCA/helpdesk/jobs/508147435). Excerpt:

```
./helpdesk_mgmt/i18n/pt_BR.po:1365:13: invalid multibyte sequence

./helpdesk_mgmt/i18n/pt_BR.po:1365:30: invalid multibyte sequence

./helpdesk_mgmt/i18n/pt_BR.po:1365:31: invalid multibyte sequence

./helpdesk_mgmt/i18n/pt_BR.po:1368:25: invalid multibyte sequence

./helpdesk_mgmt/i18n/pt_BR.po:1368:36: invalid multibyte sequence

./helpdesk_mgmt/i18n/pt_BR.po:1374:57: invalid multibyte sequence

./helpdesk_mgmt/i18n/pt_BR.po:1374:58: invalid multibyte sequence

msgmerge: found 128 fatal errors

./helpdesk_mgmt/i18n/es_AR.po:46:38: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:324:17: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:324:35: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:332:34: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:338:31: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:344:13: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:364:17: invalid multibyte sequence

./helpdesk_mgmt/i18n/es_AR.po:364:30: invalid multibyte sequence
```

this PR https://github.com/OCA/helpdesk/pull/227/ does not touch those files.... :thinking: 

Maybe is trying to merge terms from 2 different modules? :question:

**Comment by sbidoul** [comment]
I don't how that happened but these .po files definitely have character encoding issues, apparently introduced during migration: 4abe1da13f041ff302bb715e316f766ab51ea4a8

**Pull request closed without merging**
