### PR TITLE
[FIX] helpdesk_mgmt: fix error when submitting a ticket with an attachment

### LINKED ISSUE #138: [13.0] helpdesk_mgmt : adding attachment fails
Hello, 
   (at commit b2f7d3c48187c4aed7d79b59e9dbe4df6be9a8de)

   with a portal user,
   if i add an attachment while creating issue, i got redirected to following traceback :
```
Traceback (most recent call last):
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/parts/helpdesk/helpdesk_mgmt/controllers/main.py", line 74, in submit_ticket
    "res_id": new_ticket.id,
  File "<decorator-gen-130>", line 2, in create
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/addons/website/models/ir_attachment.py", line 25, in create
    return super(Attachment, self).create(vals)
  File "<decorator-gen-39>", line 2, in create
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/addons/base/models/ir_attachment.py", line 524, in create
    return super(IrAttachment, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo/parts/OCB-f54310be4efed12f74ce6e3d91251f171319894e/odoo/models.py", line 3699, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'datas_fname' on model 'ir.attachment'
```

### PR DESCRIPTION
**Pull request by davejames**
Fixes #138 which was caused by deprecated field datas_fname being included in the attachment values

### CODE REVIEW

**Comment by luffah** [comment]
The PR https://github.com/OCA/helpdesk/pull/132 seems to do the same thing.
However, your PR goes to the essentials.
(And it works at first try)

**Comment by pedrobaeza** [comment]
Isn't there any replacement for that field?

**Comment by davejames** [comment]
> Isn't there any replacement for that field?

The rationale for removing that fields seems to be that it was redundant so there is no replacement

https://github.com/odoo/odoo/pull/32976

**Review by pedrobaeza — APPROVED** [review]
OK, great, thanks for the extra explanations

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
