### PR TITLE
Module logo update

### PR DESCRIPTION
**Pull request by samuel-domatix**
- Module logo changed

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you provide as well the source file (SVG or similar)? Shouldn't we differentiate from enterprise icon with another FA icon?

**Comment by nacho-domatix** [comment]
Hi Pedro, we believe the icon is "different enough". As people say in Thailand, "same, same, but different" ;)
Anyway, is not going to create confusion at all cause even would be possible to use both (enterprise and OCA approach), I don't think that's gonna happen.

**Comment by samuel-domatix** [comment]
This is the icon SVG file.

[helpdesk_icon.zip](https://github.com/OCA/helpdesk/files/3445709/helpdesk_icon.zip)

**Comment by pedrobaeza** [comment]
Please include it in the PR in the same folder than the PNG.

**Review by pedrobaeza — APPROVED** [review]
Squashing on merge

**Review by emagdalenaC2i — APPROVED** [review]

**Pull request merged**
