### PR TITLE
[14.0][MIG]helpdesk_mgmt_rating

### PR DESCRIPTION
**Pull request by watthanun**

### CODE REVIEW

**Comment by PierrickBrun** [comment]
Hi @watthanun Can you rebase this PR and only keep modifications to `helpdesk_mgmt_rating` ?

I will need it fairly quickly so if you don't have time to work on this I'm OK with opening a new PR for it

**Comment by marcos-mendez** [comment]
@PierrickBrun sorry whats the status here? Can i help?

**Comment by PierrickBrun** [comment]
> @PierrickBrun sorry whats the status here? Can i help?

https://github.com/OCA/helpdesk/pull/248 Has been merged so I think this PR can be closed

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Pull request closed without merging**
