### PR TITLE
[12.0][IMP] helpdesk_mgmt: search tickets from both number and name

### PR DESCRIPTION
**Pull request by dalonsod**
With this improvement, default search for tickets will look into both number and name (title) ticket fields, which may be useful IMO.

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by marcelsavegnago — APPROVED** [review]

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers is this PR ready to be merged? When merged I'll port it to v13
Thanks!

**Comment by dalonsod** [comment]
> is this PR ready to be merged? When merged I'll port it to v13

@OCA/helpdesk-maintainers could you merge? Thanks!

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
