### PR TITLE
[14.0] [IMP] helpdesk_mgmt: modernize ticket portal page

### PR DESCRIPTION
**Pull request by renda-dev**
Back-port of https://github.com/OCA/helpdesk/pull/377 from v15.0 to v14.0

### CODE REVIEW

**Comment by renda-dev** [comment]
Hello @OCA/helpdesk-maintainers, since it's a back-port of an already merged PR, and also the situation of the ticket's portal UI in v14.0 it's pretty bad, would anyone mind giving this a look, please?

Every feedback it's appreciated!

**Review by PicchiSeba — APPROVED** [review]
I haven't tried it, but by inspecting the code it seems fine by me

**Comment by marcelsavegnago** [comment]
@renda-dev can you rebase please ?

**Comment by marcelsavegnago** [comment]
ping @houzefa-abba

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Comment by marcelsavegnago** [comment]
ping @rvalyi

**Review by augustodinizl — APPROVED** [review]
LGTM

**Review by douglascstd — APPROVED** [review]
[FUNCTIONAL REVIEW] - APPROVED

Operation via interface is OK.
image

There is a problem on the Group by selection:
https://github.com/OCA/helpdesk/assets/20867090/62267963-d32a-42bf-aa91-d04437930512
If we select the Stage it's work, but if we use the Category it's not working.

I undestand the main objetive is just to port to v14 this improve. So I open an issue as soom as possible

**Review by felipemotter — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers 

Can merge this ?

**Review by houzefa-abba — APPROVED** [review]
Good job! LGTM (code review only)

**Pull request merged**
