### PR TITLE
[14.0][FIX] improve performance counting tickets

### PR DESCRIPTION
**Pull request by rmorant**
Issue #475 
Performance improved creating a new ticket in a project, with already 160.000 tickets, from 45 second to less than one.

### CODE REVIEW

**Comment by dalonsod** [comment]
Hello @rmorant thanks for the contribution!

Have you considered using `read_group` instead of `search_count`, like Helpdesk Teams' ticket count?

https://github.com/OCA/helpdesk/blob/012f4a539c97e4cb63635450ef8d802b872c2e57/helpdesk_mgmt/models/helpdesk_ticket_team.py#L70C1-L99

**Comment by rmorant** [comment]
> Hello @rmorant thanks for the contribution!
> 
> Have you considered using `read_group` instead of `search_count`, like Helpdesk Teams' ticket count?
> 
> https://github.com/OCA/helpdesk/blob/012f4a539c97e4cb63635450ef8d802b872c2e57/helpdesk_mgmt/models/helpdesk_ticket_team.py#L70C1-L99

Makes sense. If there are many projects or tasks we only need two queries.
Thank you for the advice.  I have already modified it.

**Review by dalonsod — CHANGES_REQUESTED** [review]
Could you squash commits, and rename commit & PR adding addon name after `[FIX]` tag? Once done, I'll approve it

**Comment by rmorant** [comment]
> Could you squash commits, and rename commit & PR adding addon name after `[FIX]` tag? Once done, I'll approve it

Hi @dalonsod, thank you. It's ok?

**Comment by dalonsod** [comment]
There are 5 commits, and there should be only one

**Comment by rmorant** [comment]
> Could you squash commits, and rename commit & PR adding addon name after `[FIX]` tag? Once done, I'll approve it

Hi @dalonsod , sorry I'm still clumsy with git. 
Can you check it now? Thank you

**Review by dalonsod — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

Please fw-port it to upper versions

**Comment by dalonsod** [comment]
Hello @rmorant would you port this PR to v15/v16, as @pedrobaeza suggested? If not, I'll take care of it

**Comment by rmorant** [comment]
Hi @dalonsod , @pedrobaeza  FW-PORT PRs done.

**Pull request merged**
