### PR TITLE
[ADD] 14.0 helpdesk_mgmt_solution: create searchable solutions for helpdesk tickets

### PR DESCRIPTION
**Pull request by mtelahun**
This module is a port of #242 for 11.0 from elego Software Solutions GmbH.
It allows solutions to be attached to help desk tickets. These solutions
can then be searched from other tickets. They can be searched for by title,
content or attached tags.

### CODE REVIEW

**Comment by mtelahun** [comment]
Ooops, first diff was based on the wrong branch. 
Rebased from the correct branch.

**Comment by MiquelRForgeFlow** [comment]
It would be nice to have the commit history. It is explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#Howto

**Comment by mtelahun** [comment]
> It would be nice to have the commit history. It is explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#Howto

The PR for 11.0 (that this PR is based on) is a new module. It has no history to port

**Comment by MiquelRForgeFlow** [comment]
> The PR for 11.0 (that this PR is based on) is a new module. It has no history to port

No, it's not a new module, it's a migration of an existing module in v11. You can see that in https://github.com/OCA/helpdesk/pull/313, which can be easily checked that it's a purely migration of that module and not a new module, as it maintain same authors and code.

**Comment by mtelahun** [comment]
> > The PR for 11.0 (that this PR is based on) is a new module. It has no history to port
> 
> No, it's not a new module, it's a migration of an existing module in v11. You can see that in #313, which can be easily checked that it's a purely migration of that module and not a new module, as it maintain same authors and code.

Actually, the correct sequence of events is:
1. PR #242 for a new module was created in 11.0
2. I created this PR based on it (Nov. 2021)
3. PR #242 was merged  (Feb. 2022)
4. You created #313 as a migration of the module that is now merged in 11.0 (Apr. 2022)

Now that #242 is merged in 11.0 the correct thing to do is merge #313

**Comment by MiquelRForgeFlow** [comment]
> Actually, the correct sequence of events is:

Oh, I didn't know it. Thanks!

**Pull request closed without merging**
