### PR TITLE
[12.0][MIG] helpdesk_mgmt_sla

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @rvalyi @augustodinizl

**Comment by marcelsavegnago** [comment]
ping @marcos-mendez

**Review by rvalyi — APPROVED** [review]
LGTM

**Review by augustodinizl — APPROVED** [review]
LGMT

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Comment by marcelsavegnago** [comment]
ping @hgarridoco

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers can you merge please ?

**Comment by marcelsavegnago** [comment]
@pedrobaeza @DarioLodeiros can you merge please ?

**Comment by pedrobaeza** [comment]
Merging according existing reviews

/ocabot merge nobump

**Pull request merged**
