### PR TITLE
[15.0][IMP] helpdesk_mgmt_project: link kanban task with tickets

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Forward port of #411 

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
pre-commit will be fixed after https://github.com/OCA/helpdesk/pull/433 is merged.

**Comment by LoisRForgeFlow** [comment]
@DavidJForgeFlow you can rebase this pr now.

**Comment by DavidJForgeFlow** [comment]
> @DavidJForgeFlow you can rebase this pr now.

Done! Thanks @LoisRForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
