### PR TITLE
[12.0][IMP] helpdesk_type: added grouping tickets by type & some demo data

### PR DESCRIPTION
**Pull request by dalonsod**
This PR includes:

- Added `type_id` field to group section of ticket search view.
- Added some demo data.
- Fixes typo in `__manifest__.py`.

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Comment by dalonsod** [comment]
fixed typo in commit message

**Review by bodedra — APPROVED** [review]

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers is it possible to merge this PR? Thanks!

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers is this PR ready to be merged? Thanks!

**Comment by elvise** [comment]
Hi any good chance for merge it ?
@bodedra

**Comment by marcelsavegnago** [comment]
@pedrobaeza Can you merge this PR?

**Comment by marcelsavegnago** [comment]
> /ocabot merge minor

@pedrobaeza thank you 👍

**Pull request merged**
