### PR TITLE
[16.0][FIX] helpdesk_mgmt: Do not assign company_id null when creating a ticket

### PR DESCRIPTION
**Pull request by victoralmau**
Do not assign company_id null when creating a ticket

Related to https://github.com/OCA/helpdesk/commit/84353f724df47ff58afc22e64bf71722156f6679

Ping @pedrobaeza can you review it?

@Tecnativa TT50031

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Doesn't it contain the same value?

**Comment by victoralmau** [comment]
Finally, the necessary changes have been done to correct the ticket problem.

**Review by pedrobaeza — APPROVED** [review]

**Review by dalonsod — APPROVED** [review]
Only code review :+1:

**Pull request merged**
