### PR TITLE
[FIX] Allow base user to access partner data without being in a Helpdesk group

### PR DESCRIPTION
**Pull request by ypapouin**
Forward port of #167

### CODE REVIEW

**Comment by dalonsod** [comment]
@ypapouin if you want to pass travis you should call `pre-commit run -a`

**Comment by ypapouin** [comment]
@dalonsod , I'm sorry but I don't understand.
Why passing travis ? to avoid it ?
Where should I call `pre-commit run -a` ?

**Comment by dalonsod** [comment]
@ypapouin your code failed running the prettier test. You can check it here: https://travis-ci.com/github/OCA/helpdesk/jobs/395087688 , at the end of the page

v13 OCA code should be formatted with `pre-commit` tool, you should pass all travis tests if you run `pre-commit run -a` before pushing the PR, you'll need to install `pre-commit` python package first. Anyway, in this case it seems that you only need to add a missing whitespace, but the best practice is the `pre-commit` automation.

You can check this one and other conventions about v13 at this link: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by ypapouin** [comment]
Thank you for your explanations, I didn't know this tool and the OCA workflow around it.

**Review by dalonsod — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
