### PR TITLE
Issues #127 [REM] Attachment Page On Ticket View

### PR DESCRIPTION
**Pull request by EDallas89**

### CODE REVIEW

**Comment by eLBati** [comment]
https://github.com/OCA/helpdesk/issues/127#issuecomment-655548494

**Review by marcelsavegnago — APPROVED** [review]
It sure is a duplicate feature

image

**Review by DarioLodeiros — APPROVED** [review]

**Comment by DarioLodeiros** [comment]
@eLBati I'll wait until Friday to merge this in case you want disscuss it or to take any action on your instances, ok?

**Comment by eLBati** [comment]
@DarioLodeiros no problem, you can  proceed

**Pull request merged**
