### PR TITLE
[16.0][MIG] helpdesk_motive

### PR DESCRIPTION
**Pull request by adasatorres**
The api.onchange decorator has been changed to compute method for this change has been made to affect any changes in the user_id and team_id fields in the database, not only from the form.

Add test for compute method.

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]
Only code review :+1:

**Review by nramosdev — APPROVED** [review]
Great

**Comment by moitabenfdz** [comment]
@nelsonramirezs @max3903 Can you merge this, please?

**Review by hspl-niharika — APPROVED** [review]

**Comment by hspl-niharika** [comment]
LGTM
@nelsonramirezs @max3903 This module work good. I think you can merge this PR.

**Review by flotho — COMMENTED** [review]
please rebase so that CI will be triggered and the merging process will continue

**Review by flotho — APPROVED** [review]

**Review by pleirb — APPROVED** [review]
Perform the tests and it is functional!

**Pull request merged**
