### PR TITLE
[14.0][IMP] Restore the fields in the ticket creation

### PR DESCRIPTION
**Pull request by JorgeQuinteros**
Restore fields that was removed in this PR: https://github.com/OCA/helpdesk/pull/304/files

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is there any problem with that? If they are required, maybe they shouldn't

**Comment by JorgeQuinteros** [comment]
Hi @pedrobaeza ,
The way it worked until the change was that these fields were populated with the customer's information when the ticket was created.
And to preserve that functionality I think it is necessary to keep informing those fields when creating the ticket from the portal.
Because when creating the ticket from the back-end the behavior is similar, when selecting a customer, the fields are filled automatically.

**Comment by pedrobaeza** [comment]
Please put such text in the commit expanded message.

**Comment by JorgeQuinteros** [comment]
Done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
