### PR TITLE
13.0 helpdesk_mgmt: Fix attach from web interface. Attachment display added

### PR DESCRIPTION
**Pull request by juandanielp24**
Fix attach from web interface: datas_fname error
Attachment display added in web interface.
Format the Description field in web interface.

image

### CODE REVIEW

**Comment by juandanielp24** [comment]
A relationship between category and team is added. So when the user creates a ticket and selects the category, it relates it to the corresponding team and appears on the board.

image

image

tThe team is assigned automatically

**Comment by emagdalenaC2i** [comment]
Please, could you add the "[ADD-->IMP] Relationship between Category an Team" in other PR?
I think it is not related with the FIX attachment issue

**Comment by juandanielp24** [comment]
@emagdalenaC2i 
Thanks Eduardo for the comment. I already did the new PR. I didn't realize I was working in the same branch ...

**Comment by luffah** [comment]
This PR can be rebased on the commit that actually does the FIX.

Another option is to close this PR and wait the another PR https://github.com/OCA/helpdesk/pull/140  that should resolve the same issue to be merged.

**Review by DarioLodeiros — CHANGES_REQUESTED** [review]
this PR is mixed with #133 
(this is not place to team - category improvement)

**Pull request closed without merging**
