### PR TITLE
[13.0][IMP] helpdesk_mgmt_timesheet: filter tickets with activity on timesheets today

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #202

### CODE REVIEW

**Comment by dalonsod** [comment]
@marcelsavegnago @ypapouin chould you review? Thanks!

**Review by ypapouin — APPROVED** [review]
LGTM
Tested on runbot

**Review by marcelsavegnago — APPROVED** [review]

**Comment by dalonsod** [comment]
Hello @OCA/helpdesk-maintainers is this PR ready to be merged? Thanks!

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
