### PR TITLE
 [13.0][MIG] helpdesk_mgmt_timesheet

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Comment by flachica** [comment]
I migrate to 13.0 @DarioLodeiros @dalonsod

**Review by marcelsavegnago — APPROVED** [review]
Funcional Review Ok

**Review by AntoniRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]

**Review by DarioLodeiros — APPROVED** [review]
Technical and functional review! :+1:

**Comment by dalonsod** [comment]
Ouch, too late for me! Maybe I'd suggested moving fields with `onchange` methods to the new compute writable one, anyway they could be implemented in other PR.

**Comment by DarioLodeiros** [comment]
I think better new PR, because there are fields that come from different modules

**Pull request merged**
