### PR TITLE
[16.0] [MIG] helpdesk_mgmt_partner_sequence

### PR DESCRIPTION
**Pull request by pleirb**
The groups_id field is removed from res_partner_view.xml and the module works fine.

### CODE REVIEW

**Review by flotho — APPROVED** [review]
code review LGTM
Thanks

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
Please follow commit message guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

Maybe squash https://github.com/OCA/helpdesk/pull/570/commits/e73a48101e71a6c83531813160c4aad90795476b with migration commit https://github.com/OCA/helpdesk/pull/570/commits/f36e3f3941de147ef619da32296a4a1fd46e8c53.

**Comment by marcelsavegnago** [comment]
And please check commit sequence.. 

image

**Review by marcelsavegnago — CHANGES_REQUESTED** [review]
https://github.com/OCA/helpdesk/pull/570#issuecomment-2126991744

https://github.com/OCA/helpdesk/pull/570#issuecomment-2126989482

**Pull request closed without merging**
