### PR TITLE
[13.0][FIX] helpdesk_mgmt_rating: fix button_box and fa icon

### PR DESCRIPTION
**Pull request by marcelsavegnago**
cc @gdgellatly 
https://github.com/OCA/helpdesk/pull/256#issuecomment-909902684

### CODE REVIEW

**Review by gdgellatly — APPROVED** [review]
Obvious, this was creating a second button box before. Now it uses the existing

**Comment by marcelsavegnago** [comment]
ping @rvalyi @augustodinizl

**Review by marcos-mendez — APPROVED** [review]
Thanks @marcelsavegnago

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Pull request merged**
