### PR TITLE
[MIG] helpdesk_mgmt_rating: Migration to 13.0

### PR DESCRIPTION
**Pull request by cubells**
Standard migration of this pr: https://github.com/OCA/helpdesk/pull/100

Depends on: https://github.com/OCA/helpdesk/pull/117

WIP.

### CODE REVIEW

**Comment by AntoniRomera** [comment]
Anyone can try to rebuild this module to merge. @cubells

**Comment by cubells** [comment]
@AntoniRomera 
Done.

**Comment by AntoniRomera** [comment]
The runrobot gives an error because it depends on the helpdesk_mgmt module but it was already migrated. Is this behavior correct?

@cubells 
@pedrobaeza

**Comment by cubells** [comment]
@AntoniRomera It was a temporary problem. Now all it's ok.

**Comment by cubells** [comment]
@AntoniRomera It fails again, ;-(
I don't know why.

**Comment by pedrobaeza** [comment]
Have you rebased over current 13.0 branch?

**Comment by cubells** [comment]
@AntoniRomera now It's ok.

**Review by FernandoRomera — APPROVED** [review]
Functional test, Ok.

**Review by AntoniRomera — APPROVED** [review]
Functional test OK

**Review by marcelsavegnago — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]

**Comment by FernandoRomera** [comment]
@pedrobaeza @DarioLodeiros Can you merge this PR?.

**Pull request merged**
