### PR TITLE
[11.0][ADD] helpdesk_mgmt: Initial module

### PR DESCRIPTION
**Pull request by pedrobaeza**
This superseeds #1 with this extra work done on it:

* A bit of commit squashing by author for reducing the number of them.
* Deal with conflict resolution due to scrambled commit history with merge operations.
* Rename of the module to `helpdesk_mgmt` since the beginning through `git filter-branch`, like it was never called other way.
* Adjust the translation for proper module new name. It has been done in the same commit that added it.
* Fix of the README fragments, as it contains incorrect title levels.
* Regeneration of the main README.
* Set development status to alpha for meaning the work in progress.
* Adjustment of the XML-IDs.
* Added me as contributor (but not as author).

With this, if everything goes OK, we can merge it and continue doing simultaneous PRs with the rest of improvements.

### CODE REVIEW

**Comment by aitorbouzas** [comment]
XML ids are failing because of the renaming.
Model shouldn't be renamed too?

**Comment by pedrobaeza** [comment]
Yeah, didn't check that as XML-IDs shouldn't be totally qualified in XML, but in code + tests must. On my way to fix it.

**Comment by pedrobaeza** [comment]
The problem indeed were most fully qualified XML-ID references in XML files when they are not needed (they are resolved as "current module" when there are no specified module, so with this technique, you save troubles when doing things like this renaming).

Let's see now if everything is correct.

**Comment by aitorbouzas** [comment]
Oh, that's true. "Local" xml ids shouldn't need module reference...

**Comment by pedrobaeza** [comment]
Now everything is green. Can you give your final review? @aitorbouzas @emagdalenaC2i @carlosDomatix @alvaroDomatix @SamuelDomatix @miguel-domatix ?

**Review by aitorbouzas — APPROVED** [review]
LGTM
Thanks Pedro, we really appreciate your effort.

**Review by carlos-domatix — APPROVED** [review]

**Review by alvaro-domatix — APPROVED** [review]

**Review by samuel-domatix — APPROVED** [review]

**Review by miguel-domatix — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it! Thanks all for you great work and keep going with it! Let me know any doubt you have in later PRs with GIT dealing with the module renaming.

**Pull request merged**
