### PR TITLE
[IMP] Add Archive Smart Button on Tickets

### PR DESCRIPTION
**Pull request by EDallas89**
Add a smart button on helpdesk ticket view for archive/unarchive tickets

### CODE REVIEW

**Review by emagdalenaC2i — APPROVED** [review]
LGTM tested in runbot

**Review by GorkaMagra — APPROVED** [review]
Code reviewed and tested in runbot, no issues found ! Approved.

**Comment by pedrobaeza** [comment]
Please migrate it to 13.0 as well.

**Pull request merged**
