### PR TITLE
[16.0][ADD] helpdesk mgmt timesheet

### PR DESCRIPTION
**Pull request by Zararthustra**

### CODE REVIEW

**Comment by vincent-hatakeyama** [comment]
Port of #477 and improvement suggested in https://github.com/OCA/helpdesk/pull/425#pullrequestreview-1484763513

**Review by OpenCode — APPROVED** [review]

**Review by flotho — APPROVED** [review]
easy code review

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This is not `[ADD]`, but `[IMP]`. Please change commit messages.

**Comment by vincent-hatakeyama** [comment]
> This is not `[ADD]`, but `[IMP]`. Please change commit messages.

I’ve just changed them.

**Review by flotho — APPROVED** [review]
Code review
LGTM, thanks

**Comment by flotho** [comment]
could be closed because already available https://github.com/OCA/helpdesk/tree/16.0/helpdesk_mgmt_timesheet

**Comment by vincent-hatakeyama** [comment]
> could be closed because already available https://github.com/OCA/helpdesk/tree/16.0/helpdesk_mgmt_timesheet

That’s incorrect, the changes proposed in the PR have not been merged. I will open a new PR with me so I can edit have a correct title and edit the description.

**Pull request closed without merging**
