### PR TITLE
[11.0][FIX] - helpdesk_mgmt

### PR DESCRIPTION
**Pull request by yevbes**
Hidden quick creation button from the kanban view and removed the required restriction from the Description field.

[Issue fixed] -  [11.0] Issue on create new ticket in kanban view #97

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Always in English, please, and check CIs status

**Comment by yevbes** [comment]
All revised

**Review by rafaelbn — APPROVED** [review]
:+1:

**Review by dreispt — APPROVED** [review]

**Pull request merged**
