### PR TITLE
[14.0][FIX]helpdesk_mgmt: replace 'force_company' with 'with_company'

### PR DESCRIPTION
**Pull request by manuelregidor**
with_context(force_company=X) not to be used anymore. seq.with_company(X) instead.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@ValentinVinagre

**Comment by manuelregidor** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Review by albariera — COMMENTED** [review]
LGTM :+1:

**Review by albariera — APPROVED** [review]

**Review by mamcode — APPROVED** [review]

**Pull request merged**
