### PR TITLE
helpdesk_mgmt: fixed a rights issue with accessing the helpdesk.ticket.team page

### PR DESCRIPTION
**Pull request by VictorEkstrom**
fixed an issue where users with the helpdesk groups "user" and "user: personal tickets" werent able to see the helpdesk.ticket.team page as it tried to do a write to a record with the users rights, which they of course do not have the right to do.

### CODE REVIEW

**Comment by dalonsod** [comment]
Hello @VictorEkstrom . Could you take a look at #220 and #222 ?

**Comment by VictorEkstrom** [comment]
Yeah, i can port the #124 solution that was mentioned in #222 and send a new pull request if you want?

**Comment by VictorEkstrom** [comment]
I have now ported the fix from #124

**Comment by dalonsod** [comment]
Once applied the code refactoring, you shoud remove `todo_ticket_ids` field, as @gdgellatly suggested

**Comment by dalonsod** [comment]
@VictorEkstrom  the last commit appears to be wrong, not for this PR, could you check?

**Comment by VictorEkstrom** [comment]
Yeah, another guy from the office accidentally pushed some stuff to this repo, ill get it fixed

**Comment by VictorEkstrom** [comment]
Im done now though, my first fix worked, and my second fix that you ordered also works. But i cant be refactoring code for you guys at my current employers expense. Id suggest you accept my fix and if you want to do refactoring, open a new issue for it.

**Comment by pedrobaeza** [comment]
Please clean the commit history of this PR and let only one commit.

**Comment by gdgellatly** [comment]
@VictorEkstrom it worked but was wrong and introduced changed behaviour. You are being asked to make it compatible with the downstream pull requests and to provide the complete fix. It should have just been straight cherry picked / forward ported from #222. As for I'm done working for you guys, no one is paid for this. You benefit from all the hours someone else put in developing these modules, working at their employers expense and refuse to do a simple cherry pick.

@pedrobaeza I'm not sure we accept this. I think a straight forward port of #222 is better for maintaining and also more correct.

**Comment by pedrobaeza** [comment]
Yeah, I see. Indeed, as this came after, it should preserve attribution of the patch. Please both review #222 and make it to be merged, and cherry-pick such commit here and perform the needed changes (if any) for adapting it to v14.

**Comment by VictorEkstrom** [comment]
Ive cherry-picked the commits from #222 and tested it on my odoo14 machine, and it all appears to be working. Ive left it as 2 commits as that is what i found on the #222 pr and i wanted to preserve commit history, but i can merge it into one commit if you guys want me to.

I also want to apologize for my earlier outburst, this was my first time working with pull requests in this fashion, towards a big external party, and i clearly had the wrong ideas about how this works going into it. I also misunderstood exactly what it was that you wanted me to do for this pull request until @gdgellatly 's message, which cleared things up for me.

I had a lot on my plate, and stress got the better of me, i do apologize ^^

Let me know if there is anything further that i can do for this pull request.

**Comment by pedrobaeza** [comment]
@VictorEkstrom no need to worry. We all have bad days. I understand that this is sometimes not easy: a lot of new rules, weird requirements, but we try to set a common ground for all to have their reward. Imagine you do a lot of stuff here in OCA (hopefully!) and others replace your authorship with theirs, nullifying your work. That's why we ask to preserve things like that, as it's one of the most important things in open source.

**Comment by dalonsod** [comment]
Hello @VictorEkstrom , at last #222 is merged, and commit history was changed since you made cherry picking, could you check? Sorry for the inconvenience, if was my fault :(

**Comment by VictorEkstrom** [comment]
Yeah sure, ill take a look at it

**Comment by VictorEkstrom** [comment]
I believe that it should be fixed now if i understood you correctly

**Comment by VictorEkstrom** [comment]
What is the status of this pull request? Is it good enough to be merged, or is there something further that i need to do?

**Review by gdgellatly — APPROVED** [review]
LGTM - Code Review, Simple forward port

**Review by dalonsod — APPROVED** [review]
:+1:

**Review by marcelsavegnago — APPROVED** [review]

**Review by AntoniRomera — APPROVED** [review]

**Pull request merged**
