### PR TITLE
11.0_helpdesk_helpdesk_timesheet

### PR DESCRIPTION
**Pull request by agent-z28**
I dont know how the old one got deleted.

### CODE REVIEW

**Comment by agent-z28** [comment]
@aitorbouzas i readded your points
Add a small image for this? OKAY i will do now

Functional testing:

1. Missing some demo data
2. Hide or make timesheets readonly until a project is filled in ticket, if you try to add a timesheet without a project in the ticket it'll show an error not so easy to understand for users, Now the Tabs will be hidden.
3. Is 'task' field really needed for timesheets inside tickets? YES :) But its optional.

**Comment by luffah** [comment]
Note Travis CI fails because of flake8 : you just forgot to add next line on your module manifest. (line 7) 
```python
    "depends": [
        "helpdesk_mgmt",
        "hr_timesheet",
    ],
```

**Review by rafaelbn — APPROVED** [review]
:+1: 

@aitorbouzas is not in Odoo world in this moment

**Comment by elvise** [comment]
Hi, how can I help for reach merge...?

**Pull request closed without merging**
