### PR TITLE
[14.0] [IMP] helpdesk_mgmt_sla: add freeze stages  and hours freezed

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @hgarridoco @augustodinizl

**Comment by marcelsavegnago** [comment]
ping @augustodinizl

**Comment by marcelsavegnago** [comment]
ping @rvalyi

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich

**Review by augustodinizl — APPROVED** [review]
LGTM

**Pull request closed without merging**
