### PR TITLE
[16.0][MIG] helpdesk_mgmt_project migration to 16.0

### PR DESCRIPTION
**Pull request by zuher83**
Migration of helpdesk_mgmt_project addon from 15.0 to 16.0
It's based on PR #440

### CODE REVIEW

**Comment by AntoniRomera** [comment]
Can you reactivate the PR?

**Comment by zuher83** [comment]
> Can you reactivate the PR?

Voila it's done 😉 please review it

**Review by moitabenfdz — APPROVED** [review]
Functionally and code reviewed. Looks good.

**Review by ghost — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot migration helpdesk_mgmt_project

@AntoniRomera can you please review?

**Review by AntoniRomera — APPROVED** [review]
LGTM

**Pull request merged**
