### PR TITLE
[FIX] helpdesk_ticket: Load helpdesk_ticket_stage before helpdesk_ticket to enable installation on fresh DB

### PR DESCRIPTION
**Pull request by colpari**
When trying to install on a database which has never seen the model helpdesk.ticket.stage before the installation fails because helpdesk.ticket is loaded before helpdesk.ticket.stage but the first depends on the latter (via helpdesk.ticket._get_default_stage_id())
When uninstalling the helpdesk.ticket.stage model remains in DB (not sure why) so that the error never occurs again with the same DB.

This commit fixes the install issue.

Backtrace:
```
2023-03-06 17:47:56,062 1 INFO odoo odoo.modules.registry: module helpdesk_mgmt: creating or updating database tables 
2023-03-06 17:47:56,091 1 ERROR odoo odoo.sql_db: bad query: SELECT "helpdesk_ticket_stage".id FROM "helpdesk_ticket_stage" WHERE ("helpdesk_ticket_stage"."active" = true) ORDER BY  "helpdesk_ticket_stage"."sequence" ,"helpdesk_ticket_stage"."id"   LIMIT 1
ERROR: relation "helpdesk_ticket_stage" does not exist
LINE 1: SELECT "helpdesk_ticket_stage".id FROM "helpdesk_ticket_stag...
                                               ^
 
2023-03-06 17:47:56,095 1 WARNING odoo odoo.modules.loading: Transient module states were reset 
2023-03-06 17:47:56,098 1 ERROR odoo odoo.modules.registry: Failed to load registry 
2023-03-06 17:47:56,098 1 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 486, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 603, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 428, in init_models
    model._auto_init()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2835, in _auto_init
    new = field.update_db(self, columns)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2743, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 900, in update_db
    self.update_db_notnull(model, column)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 956, in update_db_notnull
    model._init_column(self.name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2755, in _init_column
    value = field.default(self)
  File "/var/lib/odoo/addons/15.0/helpdesk_mgmt/models/helpdesk_ticket.py", line 14, in _get_default_stage_id
    return self.env["helpdesk.ticket.stage"].search([], limit=1).id
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1811, in search
    return res if count else self.browse(res)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5179, in browse
    if not ids:
  File "/usr/lib/python3/dist-packages/odoo/osv/query.py", line 215, in __bool__
    return bool(self._result)
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
  File "/usr/lib/python3/dist-packages/odoo/osv/query.py", line 208, in _result
    self._cr.execute(query_str, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedTable: relation "helpdesk_ticket_stage" does not exist
LINE 1: SELECT "helpdesk_ticket_stage".id FROM "helpdesk_ticket_stag...
                                               ^


```

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]

**Comment by dalonsod** [comment]
@colpari could you reword commit making it start with `[FIX] helpdesk_ticket: ...` ?

**Comment by colpari** [comment]
@dalonsod : sorry, we missed this request. We changed the title

**Comment by pedrobaeza** [comment]
I'm reading the problem, and it's not a real problem, as if so, the CI and runboat, that installs the module from scratch, will fail with the same problem, so it should be something on your side.

**Comment by colpari** [comment]
@pedrobaeza : What you are saying absolutely makes sense :-D
We just tried to reproduce with a completely fresh install - and we're unable to.

I don't remember the exact context this happened 9 months ago (and was fixed for us by re-ordering __init__.py) but obviously there must have been some outside cause for helpdesk.ticket.init()  running before helpdesk.ticket.stage.init()

Sorry for wasting you'r guys time :-\ I'll close this for now.

**Pull request closed without merging**
