### PR TITLE
[14.0][FIX] Avoid error when creating ticked from a duplicated customer

### PR DESCRIPTION
**Pull request by JorgeQuinteros**
When the client tries to create a ticket from the portal and it has a duplicate contact:
Captura de pantalla 2022-02-20 185514

It throws the **following error**:
Captura de pantalla 2022-02-20 190445

### CODE REVIEW

**Review by Jesarregui — APPROVED** [review]
LGTM. Technical Review

**Comment by pedrobaeza** [comment]
The submit ticket can be used without being logged in?

**Comment by JorgeQuinteros** [comment]
> The submit ticket can be used without being logged in?

Hi @pedrobaeza , 
No, you must be logged in to submit a ticket.

**Comment by pedrobaeza** [comment]
Then what should be removed as well is the name and email fields in such form. They should be taken from the user.

**Comment by JorgeQuinteros** [comment]
> Then what should be removed as well is the name and email fields in such form. They should be taken from the user.

Yes, you are right. also the email is read only so it's a bit redundant knowing you have to log in to create a ticket. I'll update the changes tonight, thanks.

**Review by valentincastravete — APPROVED** [review]
LGTM! Technical Review

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please fw-port it to v15?

**Comment by pedrobaeza** [comment]
Cherry-picked to v13 as well at 921c9f6b926bc0752a679df488bfa99294bfa0d5

**Pull request merged**
