### PR TITLE
[FIX] helpdesk_mgmt: add write permission for portal user

### PR DESCRIPTION
**Pull request by davejames**
Fixes issue #137 where where permission error was encountered when portal user tries to add a message to their ticket

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think this is the solution, or at least not without an extra record rule.

**Comment by davejames** [comment]
> I don't think this is the solution, or at least not without an extra record rule.

Where do you see the issue? There is already a record rule applicable to portal users

`        <record id="helpdesk_ticket_rule_portal" model="ir.rule">
            <field name="name">Portal Personal Tickets</field>
            <field name="model_id" ref="model_helpdesk_ticket" />
            <field
                name="domain_force"
            >[('message_partner_ids','child_of',[user.commercial_partner_id.id])]</field>
            <field name="groups" eval="[(4, ref('base.group_portal'))]" />
        </record>
`

**Comment by pedrobaeza** [comment]
OK, if there is a record rule, then the access is limited. Any way, I would check for how it's done in other models like `sale.order` for letting users to write messages.

**Comment by davejames** [comment]
@pedrobaeza you're right, I found a better solution

**Comment by davejames** [comment]
@pedrobaeza @DarioLodeiros would you be able to review this? It's just a one-liner but it fixes the bug

**Review by pedrobaeza — APPROVED** [review]

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
