### PR TITLE
[12.0][IMP] helpdesk_mgmt_timesheet: filter tickets with activity on timesheets today

### PR DESCRIPTION
**Pull request by dalonsod**
With this improvement, it's easy to find out tickets with recent activity on timesheets

### CODE REVIEW

**Comment by dalonsod** [comment]
@marcelsavegnago @watthanun could you review? Thanks!

**Review by lmiguens-solvos — APPROVED** [review]
Tested in runbot. LGTM

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers is this PR ready to be merged? Thanks!

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
