### PR TITLE
[12.0][IMP] helpdesk_mgmt_sla: add freezed stages and freezed hours

### PR DESCRIPTION
**Pull request by marcelsavegnago**
ping @augustodinizl @marcos-mendez

### CODE REVIEW

**Review by marcos-mendez — APPROVED** [review]
Aprovando

**Review by antoniospneto — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich

**Comment by etobella** [comment]
@marcelsavegnago Might be possible to add some tests on this change?

**Pull request closed without merging**
