### PR TITLE
[15.0][FIX] helpdesk_mgmt: assigned date empty and creation method to multi

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Forward port of #409 

@ForgeFlow

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase instead of pulling for avoiding the merge commit, and version number shouldn't be included in the commit message.

**Comment by pedrobaeza** [comment]
The version is still in the commit messages.

**Comment by DavidJForgeFlow** [comment]
> The version is still in the commit messages.

Fixed! Thanks @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please check an extra line that is around, David, and it's making pre-commit to fail.

**Pull request merged**
