### PR TITLE
[REN] helpdesk_mgmt

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
@aitorbouzas I could not do the PR neither to https://github.com/aitorbouzas/helpdesk nor to https://github.com/aitorbouzas/OCA-helpdesk

### CODE REVIEW

**Comment by aitorbouzas** [comment]
@emagdalenaC2i that's because your branch has been cloned from this, and not from mine

**Comment by pedrobaeza** [comment]
But if the PR is not yet merged, this can't be merged. The idea is to create the pull request over @aitorbouzas's branch instead for appearing in the main PR.

**Comment by aitorbouzas** [comment]
@emagdalenaC2i will you please do this PR into my repo?

**Comment by emagdalenaC2i** [comment]
@aitorbouzas done, but there are some conflicting files now

**Comment by aitorbouzas** [comment]
Ok, close this. We'll manage the renaming in https://github.com/aitorbouzas/OCA-helpdesk/pull/15

**Pull request closed without merging**
