### PR TITLE
[13.0][IMP] helpdesk_type: added search, grouping tickets by type, some demo data and proper icon

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #203 and some additions:
- Added field search and grouping by type.
- Some demo data
- Switched addon icon to OCA official one.

### CODE REVIEW

**Comment by dalonsod** [comment]
@max3903 @ypapouin could you review? Thanks!

**Review by marcelsavegnago — APPROVED** [review]

**Review by albariera — APPROVED** [review]
Technical review LGTM :+1:

**Review by bodedra — APPROVED** [review]

**Comment by dalonsod** [comment]
@dreispt could you check why did merge fail? Looking at https://app.travis-ci.com/github/OCA/helpdesk/jobs/527466045 I've only seen this error, but I'm not sure if I'm right and how to solve it:

>remote: Password authentication is temporarily disabled as part of a brownout. Please use a personal access token instead.
>remote: Please see https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/ for more information.
>fatal: unable to access 'https://github.com/OCA/helpdesk/': The requested URL returned error: 403

**Pull request merged**
