### PR TITLE
[12.0] [FIX] Ticket creation from portal - message_subscribe_users > message_subscribe

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Ticker portal creation

- Fix message_subscribe_user > message_subscribe

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems it still continues in red. Why do you want to do this change?

**Comment by marcelsavegnago** [comment]
> It seems it still continues in red. Why do you want to do this change?

The message_subscribe_users function has apparently changed to message_subscribe. When I try to create a ticket via portal Odoo returns that this function does not exist in version 12.0.

About the error reported by Travis I do not know what it can be.

**Comment by luffah** [comment]
I (as a low rank contributor) approve this change.

**Comment by luffah** [comment]
Shall Ticket category be mandatory in portal while it is not in model ?

**Comment by marcelsavegnago** [comment]
> It seems it still continues in red. Why do you want to do this change?

@pedrobaeza Can you guide me regarding the error occurred in Travis? I honestly do not understand what it can be :) sorry

**Comment by luffah** [comment]
Since the PR is not validated yet. Why limit access to button "new ticket" to the restrictive group "portal user", given only these users could see the list  and portal home? (it remove the possibility to test as admin)

**Comment by pedrobaeza** [comment]
The problem is:
```
helpdesk_mgmt/controllers/main.py:56:80: E501 line too long (81 > 79 characters)
```

**Review by pedrobaeza — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
> Since the PR is not validated yet. Why limit access to button "new ticket" to the restrictive group "portal user", given only these users could see the list and portal home? (it remove the possibility to test as admin)

@luffah I prefer to focus on fixing this problem first so that I can release the fix as soon as possible. What do you think about submitting a new PR? I think working with minor corrections speeds up the process. But, I may be wrong.

**Review by emagdalenaC2i — APPROVED** [review]

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
