### PR TITLE
[14.0][MIG] helpdesk_motive

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration + some improvements:
- Demo dato
- Enabled motive definition from teams
- Fixed addon icon

### CODE REVIEW

**Review by raistdev — APPROVED** [review]

**Review by albariera — APPROVED** [review]
Technical review LGTM :+1:

**Review by ChristianSantamaria — APPROVED** [review]
LGTM

**Review by HaraldPanten — APPROVED** [review]

**Comment by dalonsod** [comment]
Rebase made due to #237 , nothing changed in the addon

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers could you merge this PR? Thanks!

**Comment by AntoniRomera** [comment]
@pedrobaeza @DarioLodeiros could you merge this PR #232 #236 ? Thanks!

**Comment by dalonsod** [comment]
@DarioLodeiros an ocabot merge should be run again?

**Comment by AntoniRomera** [comment]
@DarioLodeiros Can you check this, I don't quite understand why this happened.

**Pull request merged**
