### PR TITLE
[15.0][IMP] helpdesk_mgmt: tags - visual and functional adjustments

### PR DESCRIPTION
**Pull request by dalonsod**
Included in this PR:
* Tickets tree: added tags, as optional field.
* Tickets search view: added tags grouping functionality.
* Tickets form: usage of tag colors.
* Tags form: replaced old archive/active button by ribbon.
* Tags view: added active field.

### CODE REVIEW

**Comment by dalonsod** [comment]
@rmorant @SergiCForgeFlow could you review? Thanks!

**Review by rmorant — COMMENTED** [review]
All checked ok. Just, about "Archived" filter. Forgot it or not necessary?

**Comment by dalonsod** [comment]
"Archive" filter already exists... are you talking about "Active" filter instead? I could add it as well.

**Comment by rmorant** [comment]
I mean, a quick show of archived tickets
Like "Project > Tasks > Filters > 'Archived' ".

**Comment by dalonsod** [comment]
OK... this PR is all about tags improvements/missing features. Anyway, this could be added in other PR

**Review by rmorant — APPROVED** [review]

**Comment by SergiCForgeFlow** [comment]
LGTM @dalonsod

**Review by SergiCForgeFlow — APPROVED** [review]

**Comment by dalonsod** [comment]
@pedrobaeza is this PR ready to be merged? Once done, I'll port it to v16

**Pull request merged**
