### PR TITLE
[12.0] FIX helpdesk_mgmt when creating ticket from a duplicated customer:

### PR DESCRIPTION
**Pull request by eLBati**
```
  File "helpdesk_mgmt/controllers/main.py", line 55, in submit_ticket
    ('email', '=', kw.get('email'))]).id
  File "odoo/odoo/fields.py", line 2900, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: res.partner(23191, 23894)
```

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by dalonsod — APPROVED** [review]
LGTM

**Comment by gdgellatly** [comment]
@eLBati are we sure this is the right way to go? I mean it resolves 1 error to potentially cause another. Given the controller is auth=user and the email field isn't editable, shouldn't request.env.user's first partner id be our first choice id? In fact it seems strange that we search on name/ allow name to be editable at all here.

**Review by gdgellatly — CHANGES_REQUESTED** [review]
I think given that just 2 lines lower we use env.user.partner_id.ids and auth=user for the route, and email field can't be edited actually this search is somewhat pointless, and limiting to 1, potentially picks wrong partner.  For me it should just be env.user.partner_ids[0] obviously checked for empty but I think it is pretty much mandatory.

**Comment by eLBati** [comment]
@gdgellatly right. Modified. Thanks

**Review by gdgellatly — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]

**Comment by eLBati** [comment]
merge?

**Pull request merged**
