### PR TITLE
[14.0][MIG]helpdesk_mgmt_timesheet

### PR DESCRIPTION
**Pull request by watthanun**
waiting for merge helpdesk_mgmt #179

### CODE REVIEW

**Comment by dalonsod** [comment]
@watthanun looking at the files you've made the migration for both `helpdesk_mgmt` and `helpdesk_mgmt_timesheet`, and that's not recommended. And `helpdesk_mgmt` migration is already in progress, see #179 .

You should remove `helpdesk_mgmt` files and make this PR dependent on #179, or wait until the related PR is merged

**Comment by elvise** [comment]
@watthanun any chance for this PR ?

**Comment by dalonsod** [comment]
hello @elvise this addon is already migrated, see at https://github.com/OCA/helpdesk/tree/14.0/helpdesk_mgmt_timesheet

@OCA/helpdesk-maintainers could you close this? Thanks!

**Comment by elvise** [comment]
@pedrobaeza can we close this PR ?

**Pull request closed without merging**
