### PR TITLE
[16.0] [FIX] helpdesk_mgmt: use company of team on tickets when team is defined

### LINKED ISSUE #543: wrong company assignment on ticket creation
## Module
Helpdesk Management

## Describe the bug
I've created several ticket teams under 3 different companies. For some reason some tickets are assigned to the wrong company. I couldn't track the source of the problem and this looks like a bug.

## To Reproduce
**Affected versions**:
Odoo 16.0-20230629 (Community Edition)

1. Setup 3+ companies
2. Create 6+ ticket teams and assign companies arbitrary
3. Start receiving emails until some of the tickets will be assigned with the wrong company

**Expected behavior**
On creation tickets assigned to the company owning a ticket team 100% of the time

**Additional context**
I've been working with Odoo for 4-5 months already and it doing great so far. I've been seeing tickets assigned wrong for a while now but I haven't paid much attention to it until I realized that I've answered with a wrong company logo and signature a few times. I've tried to research settings and relations of models to track down the problem myself but with no success so far.  I would appreciate any help to track down the source of the problem

### PR DESCRIPTION
**Pull request by ByteMeAsap**
Fixes https://github.com/OCA/helpdesk/issues/543

### CODE REVIEW

**Review by flotho — CHANGES_REQUESTED** [review]
Hi,
thanks for the contribution.
Code revie OK
Yet, the commit name are not correct nor the issue nme.
please adapt following https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by ByteMeAsap** [comment]
> Hi, thanks for the contribution. Code revie OK Yet, the commit name are not correct nor the issue nme. please adapt following https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

@flotho ,updated the commit and PR name

**Review by flotho — APPROVED** [review]

**Comment by Jan-Onestein** [comment]
Works on this end, thank a lot  @ByteMeAsap !!!
Please merge asap @flotho  !!
@pedrobaeza can you do something from your end ?

**Review by Jan-Onestein — APPROVED** [review]
Working on multicomp setup like intenden now!!!
Thanks  @ByteMeAsap !!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by eLBati** [comment]
Porting to v15 with https://github.com/OCA/helpdesk/pull/622

**Pull request merged**
