### PR TITLE
[13.0][IMP] helpdesk_mgmt: prepare ticket number generation

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #160

### CODE REVIEW

**Review by bodedra — APPROVED** [review]

**Review by DarioLodeiros — APPROVED** [review]

**Comment by dalonsod** [comment]
@DarioLodeiros is it ready to be merged? Thanks!!

**Comment by dalonsod** [comment]
@OCA/helpdesk-maintainers could anyone merge this PR? Thanks!

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
