### PR TITLE
[12.0] Show ticket number in portal pages

### PR DESCRIPTION
**Pull request by eLBati**
Because ticket number is communicated in email

### CODE REVIEW

**Review by wytzejan — APPROVED** [review]
LGTM. Both functional and code review done.

**Comment by dalonsod** [comment]
Possible duplicate #211

**Comment by wytzejan** [comment]
@dalonsod  You are right. I believe the implementation of the `<a t-attf-href="/my/ticket/#{ticket.id}..` is better in this merge request.

**Review by dalonsod — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by mileo — APPROVED** [review]

**Review by AntoniRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@pedrobaeza Can you merge this PR? I want to migrate to V13

**Comment by eLBati** [comment]
@dreispt could you retry?
Thanks

**Pull request merged**
