### PR TITLE
[15.0][FIX] helpdesk_mgmt: Fix share action on tickets.

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 14.0: https://github.com/OCA/helpdesk/pull/323

Fix share action on tickets.

Please @chienandalu and @CarlosRoca13 can you review it?

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Add also the other commit as well

**Review by chienandalu — APPROVED** [review]

**Comment by chienandalu** [comment]
> Add also the other commit as well

The other module isn't migrated so no need for it :)

**Comment by pedrobaeza** [comment]
OK, please check pre-commit. You need to add a `return`.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
