### PR TITLE
[16.0][IMP] helpdesk_mgmt_timesheet: add optional ticket field in view and add avatar widget

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**
Port of #477 and improvement suggested in https://github.com/OCA/helpdesk/pull/425#pullrequestreview-1484763513

### CODE REVIEW

**Comment by vincent-hatakeyama** [comment]
Replaces #506

**Comment by marcelsavegnago** [comment]
@vincent-hatakeyama, I'm sorry about the confusion and for closing your PR. I didn't check the commits and mistakenly believed it was related to the module inclusion. Thank you for your contribution. #506

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by flotho** [comment]
sadly impossible to test on ruboat : 
image

even if it looks Ok : 
image

Can't properly end the review,

Regards

**Comment by marcelsavegnago** [comment]
> sadly impossible to test on ruboat : image
> 
> even if it looks Ok : image
> 
> Can't properly end the review,
> 
> Regards

try again please

**Review by flotho — APPROVED** [review]
functionnal OK
Code review OK
LGTM
Thanks

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
