### PR TITLE
[12.0][IMP] helpdesk_mgmt: prepare ticket number generation

### PR DESCRIPTION
**Pull request by dalonsod**
With this preparing code it'd be possible to make future improvements on ticket number generation. In fact, I'm developing a new addon that enables to set different ticket number sequences depending on the ticket partner

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @DarioLodeiros @eLBati

**Review by eLBati — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by dalonsod** [comment]
@DarioLodeiros could you check if this PR is ready to merge? Thanks!

**Review by DarioLodeiros — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Comment by DarioLodeiros** [comment]
/ocabot merge minor

@dalonsod  Could you forward-port it to v13? :D

**Comment by dalonsod** [comment]
> @dalonsod Could you forward-port it to v13? :D

Sure!

**Comment by dalonsod** [comment]
@DarioLodeiros open #168

**Pull request merged**
