### PR TITLE
[14.0][BACKPORT]helpdesk_mgmt: add archived ribbon to ticket stage form view

### PR DESCRIPTION
**Pull request by PicchiSeba**

### CODE REVIEW

**Comment by dalonsod** [comment]
Hello @PicchiSeba , thanks for the contribution!

This is already done for v15 in #486 . Could you check if it could be backported from it?

**Comment by PicchiSeba** [comment]
Hello @dalonsod , i cherrypicked the commit you linked, to preserve the same changes.

Let me know if I need to change anything else

**Review by dalonsod — APPROVED** [review]
Tested in runboat :+1:

**Review by HekkiMelody — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
