### PR TITLE
[ADD] Email templates for closed tickets and changed state.

### PR DESCRIPTION
**Pull request by miguel-domatix**
send an email if the ticket reaches a stage that has the associated template.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I miss:

* Use standard mail notification template as base for better design.
* Associate the template to the demo/data stages

**Comment by miguel-domatix** [comment]
https://github.com/odoo/odoo/blob/11.0/addons/sale/data/mail_template_data.xml

A template like this?

**Comment by pedrobaeza** [comment]
What about this other one that seems more beautiful (but this is an opinion)?

https://github.com/odoo/odoo/blob/1a62c2ed475d74c30222c30ec79aa4bdcdbca184/addons/sale/data/mail_template_data.xml#L65

About translations, the problem is that they can conflict as it has happened, so better to not translate in the same PR, but do it on Weblate.

**Comment by pedrobaeza** [comment]
You have committed several merges, provoking conflicts

**Comment by miguel-domatix** [comment]
We are closing this PR and opening another one in order to make the PR in the correct way.
Sorry for the inconvenience.

**Pull request closed without merging**
