### PR TITLE
[13.0][IMP] helpdesk_mgmt: search tickets from both number and name

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #200

### CODE REVIEW

**Comment by dalonsod** [comment]
@cesarlr @flachica could you review? Thanks!

**Review by marcelsavegnago — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by ypapouin — APPROVED** [review]
Make sense 👍

**Review by flachica — APPROVED** [review]

**Review by flachica — APPROVED** [review]

**Review by flachica — APPROVED** [review]

**Review by flachica — APPROVED** [review]

**Comment by bodedra** [comment]
@OCA/helpdesk-maintainers

**Comment by eLBati** [comment]
This only improves searching where `helpdesk_ticket_view_search` is involved.
https://github.com/OCA/helpdesk/pull/214 improves every search, including relational fields

**Pull request merged**
