### PR TITLE
[15.0][MIG]helpdesk motive

### PR DESCRIPTION
**Pull request by adasatorres**
Change onchange per compute, and created tests.

### CODE REVIEW

**Review by moitabenfdz — CHANGES_REQUESTED** [review]
The code LGTM and it works, but you should squash the administrative commits. 
Check this -> https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Review by max3903 — APPROVED** [review]

**Pull request merged**
