### PR TITLE
[WIP][12.0] Base for website_helpdesk

### PR DESCRIPTION
**Pull request by ananiasfilho**
Allow portal users to create helpdesk tickets from website

### CODE REVIEW

**Comment by pedrobaeza** [comment]
AFAIK, this is already done. @carlosDomatix can you confirm?

**Comment by mileo** [comment]
> AFAIK, this is already done. @carlosDomatix can you confirm?

I remember @ericflaux  from @Osiell saying that someone was working on it during oca days. but could not find the pull request.

**Comment by DarioLodeiros** [comment]
Its avail on the portal page:
https://github.com/OCA/helpdesk/blob/12.0/helpdesk_mgmt/controllers/main.py#L27
In this record you can view the original portal form ticket creation, and then, the option in this PR (I think that is better continue with the original option... ??)
HelpDeskTicketWebSitePortal

**Comment by carlos-domatix** [comment]
> AFAIK, this is already done. @carlosDomatix can you confirm?

Yes, this is already done, as @DarioLodeiros has shown.

**Comment by DarioLodeiros** [comment]
I have a doubt with this question on v13... its better to integrate de ticket creation form with the core form editor registry released on 13.0?
Example with recruitment:
https://github.com/OCA/OCB/blob/13.0/addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js#L9

**Comment by pedrobaeza** [comment]
Why don't you put that on the migration issue?

**Pull request closed without merging**
