### PR TITLE
17.0 mig helpdesk mgmt [WIP]

### PR DESCRIPTION
**Pull request by imlopes**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's #638

**Comment by giarve** [comment]
@imlopes if you want to continue this PR let me know. It is probably better than mine as I failed to merge  some cherry picked commits made between the first migration and mine and some names are not appearing in contributors. If you manage to add my fixes from the last commits you will save me time.

**Comment by imlopes** [comment]
@giarve your PR is nice. Ive started this one before check if a running migration was started. I think Ill close this PR and maybe if you prefer, I can (re)check yours.

**Comment by giarve** [comment]
> @giarve your PR is nice. Ive started this one before check if a running migration was started. I think Ill close this PR and maybe if you prefer, I can (re)check yours.

I fixed it now. You can close this one if you prefer and let me know if you find something not working in mine. Thank you

**Comment by imlopes** [comment]
Best PR: https://github.com/OCA/helpdesk/pull/638

**Pull request closed without merging**
