### PR TITLE
[IMP] - helpdesk_mgmt_fieldservice_equipment

### PR DESCRIPTION
**Pull request by marcos-mendez**
This module creates the possibility to open a HelpDesk ticket to specific Equipment in a Field-Service location. Must be used with FSM & Maintenance together

If something is wrong please just informe so i can change it

### CODE REVIEW

**Comment by marcos-mendez** [comment]
@marcelsavegnago can you help me? All this tests are some alien knowledge for me, can you explain how should i proceed?

**Comment by marcelsavegnago** [comment]
@marcos-mendez Does this module not depend on helpdesk_mgmt_fieldservice ?

**Comment by marcelsavegnago** [comment]
> All this tests are some alien knowledge for me, can you explain how should i proceed?

@marcos-mendez I recommend taking a look at some OCA modules. There are many tests that can serve as an example

**Comment by marcelsavegnago** [comment]
@marcos-mendez please execute the pre-commit command

**Pull request closed without merging**
