### PR TITLE
[14.0][FW-PORT] helpdesk_mgmt: Sequence field added to sort tickets

### PR DESCRIPTION
**Pull request by ypapouin**
This PR has been split from #448

- Sequence field added to allow kanban reordering.

### CODE REVIEW

**Review by HekkiMelody — APPROVED** [review]

**Comment by pedrobaeza** [comment]
No sequence in the tree view with widget=handle?

I think also that the priority field should be first in the tree, as it affects order.

**Comment by ypapouin** [comment]
Sequence field if now available in the list view.

I've also added a commit to mimic the Odoo 14.0 design (using `decoration-bf="1"`, `optional="..."`, `widget="remaining_days"`, `widget="many2one_avatar_user"`, `widget="badge"`)

image

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Comment by pedrobaeza** [comment]
Now please fw-port it to upper versions.

**Pull request merged**
