### PR TITLE
[13.0][MIG] helpdesk_mgmt

### PR DESCRIPTION
**Pull request by max3903**
#96

### CODE REVIEW

**Comment by rvalyi** [comment]
I see a huge diff. Is that using Black auto-formatting? If yes I think it should be done in a separate commit from the migration commit...

**Comment by emagdalenaC2i** [comment]
@max3903 could you rebase and add the pre-commit
https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

**Comment by max3903** [comment]
@emagdalenaC2i @rvalyi Will do but I have customer requests to deal with first, so it may take days or weeks. If you want to take it from here or start the migration over from scratch, be my guest. No hard feeling.

**Comment by emagdalenaC2i** [comment]
ok @max3903 
I will start the migration, maybe you can review and help later. Thanks

**Comment by pedrobaeza** [comment]
Superseded by #104

**Pull request closed without merging**
