### PR TITLE
[14.0][MIG] helpdesk_mgmt_solution (added commit history)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Same as https://github.com/OCA/helpdesk/pull/284 but with commit history.

### CODE REVIEW

**Comment by elvise** [comment]
@MiquelRForgeFlow good PR! 
Do you plan to finish it ?

**Comment by MiquelRForgeFlow** [comment]
@elvise Isn't it finished?

**Comment by elvise** [comment]
@MiquelRForgeFlow i’m sorry i was traveling 

I would like fix the UI and UX, let me try to explain

Solution Form (view.helpdesk.solution.form):
IMG_0008

Ticket form:
There is too much space there 
IMG_0009


What do you think ?

**Comment by MiquelRForgeFlow** [comment]
@elvise your suggestions have been applied :)

**Comment by elvise** [comment]
> @elvise your suggestions have been applied :)

Woow thanks! :) 

If it’s possible put there summernote ;) 
IMG_0012


In the meantime  i’m testing these buttons, from user perspective looks there is something contro intuitive, i will update you soon 

IMG_0013

**Comment by MiquelRForgeFlow** [comment]
> If it’s possible put there summernote ;)

I don't understand what do you mean. can you put an example?

**Comment by elvise** [comment]
> > If it’s possible put there summernote ;)
> 
> I don't understand what do you mean. can you put an example?

Just the rich text editor, like this one:
IMG_0014

**Pull request closed without merging**
