### PR TITLE
[15.0][IMP] helpdesk_mgmt: Only show tickets of the user's helpdesk team with "User: Team tickets" permission

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 14.0: https://github.com/OCA/helpdesk/pull/418

Only show tickets of the user's helpdesk team with "`User: Team tickets`" permission (related to https://github.com/OCA/helpdesk/pull/395#pullrequestreview-1229370921)

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT41172

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@victoralmau 

```
2023-01-17 11:18:55,765 250 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.helpdesk_type.tests.test_helpdesk_type.TestHelpdeskType)
Traceback (most recent call last):
  File "/__w/helpdesk/helpdesk/helpdesk_type/tests/test_helpdesk_type.py", line 8, in setUpClass
    env = cls.env(user=cls.user_admin)
AttributeError: type object 'TestHelpdeskType' has no attribute 'user_admin'
```

**Comment by victoralmau** [comment]
> @victoralmau
> 
> ```
> 2023-01-17 11:18:55,765 250 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.helpdesk_type.tests.test_helpdesk_type.TestHelpdeskType)
> Traceback (most recent call last):
>   File "/__w/helpdesk/helpdesk/helpdesk_type/tests/test_helpdesk_type.py", line 8, in setUpClass
>     env = cls.env(user=cls.user_admin)
> AttributeError: type object 'TestHelpdeskType' has no attribute 'user_admin'
> ```

Thanks, solved.

**Pull request merged**
