### PR TITLE
Test if ticket_id is not empty

### PR DESCRIPTION
**Pull request by cesarlr**

### CODE REVIEW

**Comment by cesarlr** [comment]
@rvalyi @ovnicraft  @pniederlag @cmayo Is it ok?

**Comment by dalonsod** [comment]
@cesarlr please check how this issue was solved in v13: https://github.com/OCA/helpdesk/commit/38247a773f9e02152ebe7d27a2d74e95268be173

**Comment by cesarlr** [comment]
Changed! Thanks @dalonsod!

**Review by ovnicraft — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by bodedra — APPROVED** [review]
:+1:

**Review by dalonsod — APPROVED** [review]
:+1:  please squash commits

**Comment by cesarlr** [comment]
> +1 please squash commits

Done! Ready to merge?

**Comment by cesarlr** [comment]
@pedrobaeza We need to merge. Can you help us?

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please fw-port it to v13

**Pull request merged**
