### PR TITLE
[MIG][16.0] helpdesk_mgmt_rating: Migration to 16.0

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]
Functional test

**Review by MRomeera — APPROVED** [review]
LGTM

**Comment by AntoniRomera** [comment]
@OCA/helpdesk-maintainers Anyone can merge?

**Review by hspl-niharika — APPROVED** [review]

**Comment by hspl-niharika** [comment]
LGTM
@AntoniRomera @DarioLodeiros I think It's good. I think you can merge this.

**Comment by carolinafernandez-tecnativa** [comment]
@pedrobaeza this PR was already approved, could you merge it?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
- The automatic changes should be split from the manual ones according the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0
- noupdate=1 changes should be reflected in a migration script loading these changes.

**Pull request closed without merging**
