### PR TITLE
[16.0][MIG] helpdesk_mgmt_timesheet: Migration 16.0

### PR DESCRIPTION
**Pull request by AntoniRomera**
Depends on OCA/project#1148

### CODE REVIEW

**Comment by AntoniRomera** [comment]
@pedrobaeza  New PR with all the funcionality

**Comment by manuelcalerosolis** [comment]
Trying to install the module gives me the following error:

odoo_1                        | View error context:
odoo_1                        | '-no context-'
odoo_1                        | 
odoo_1                        | 2023-07-14 08:23:59,433 1 ERROR alfinf odoo.http: Exception during request handling. 
odoo_1                        | Traceback (most recent call last):
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1998, in __call__
odoo_1                        |     response = request._serve_db()
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1584, in _serve_db
odoo_1                        |     return service_model.retrying(self._serve_ir_http, self.env)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
odoo_1                        |     result = func()
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1611, in _serve_ir_http
odoo_1                        |     response = self.dispatcher.dispatch(rule.endpoint, args)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1815, in dispatch
odoo_1                        |     result = self.request.registry['ir.http']._dispatch(endpoint)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
odoo_1                        |     result = endpoint(**request.params)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 697, in route_wrapper
odoo_1                        |     result = endpoint(self, *args, **params_ok)
odoo_1                        |   File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 46, in call_button
odoo_1                        |     action = self._call_kw(model, method, args, kwargs)
odoo_1                        |   File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
odoo_1                        |     return call_kw(request.env[model], method, args, kwargs)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/api.py", line 461, in call_kw
odoo_1                        |     result = _call_kw_multi(method, model, args, kwargs)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/api.py", line 448, in _call_kw_multi
odoo_1                        |     result = method(recs, *args, **kwargs)
odoo_1                        |   File "<decorator-gen-74>", line 2, in button_immediate_install
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
odoo_1                        |     return method(self, *args, **kwargs)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
odoo_1                        |     return self._button_immediate_function(type(self).button_install)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
odoo_1                        |     registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
odoo_1                        |   File "<decorator-gen-14>", line 2, in new
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 87, in locked
odoo_1                        |     return func(inst, *args, **kwargs)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new
odoo_1                        |     odoo.modules.load_modules(registry, force_demo, status, update_module)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules
odoo_1                        |     processed_modules += load_marked_modules(cr, graph,
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
odoo_1                        |     loaded, processed = load_module_graph(
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 231, in load_module_graph
odoo_1                        |     load_data(cr, idref, mode, kind='data', package=package)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 71, in load_data
odoo_1                        |     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 763, in convert_file
odoo_1                        |     convert_xml_import(cr, module, fp, idref, mode, noupdate)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
odoo_1                        |     obj.parse(doc.getroot())
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 749, in parse
odoo_1                        |     self._tag_root(de)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 709, in _tag_root
odoo_1                        |     raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo_1                        | odoo.tools.convert.ParseError: while parsing /opt/odoo/auto/addons/helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml:33
odoo_1                        | Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition
odoo_1                        | 
odoo_1                        | View error context:
odoo_1                        | '-no context-'

**Comment by AntoniRomera** [comment]
> Trying to install the module gives me the following error:
> 
> odoo_1 | View error context: odoo_1 | '-no context-' odoo_1 | odoo_1 | 2023-07-14 08:23:59,433 1 ERROR alfinf odoo.http: Exception during request handling. odoo_1 | Traceback (most recent call last): odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1998, in **call** odoo_1 | response = request._serve_db() odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1584, in _serve_db odoo_1 | return service_model.retrying(self._serve_ir_http, self.env) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying odoo_1 | result = func() odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1611, in _serve_ir_http odoo_1 | response = self.dispatcher.dispatch(rule.endpoint, args) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1815, in dispatch odoo_1 | result = self.request.registry['ir.http']._dispatch(endpoint) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch odoo_1 | result = endpoint(**request.params) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/http.py", line 697, in route_wrapper odoo_1 | result = endpoint(self, *args, **params_ok) odoo_1 | File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 46, in call_button odoo_1 | action = self._call_kw(model, method, args, kwargs) odoo_1 | File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw odoo_1 | return call_kw(request.env[model], method, args, kwargs) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/api.py", line 461, in call_kw odoo_1 | result = _call_kw_multi(method, model, args, kwargs) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/api.py", line 448, in _call_kw_multi odoo_1 | result = method(recs, *args, **kwargs) odoo_1 | File "", line 2, in button_immediate_install odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log odoo_1 | return method(self, *args, **kwargs) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install odoo_1 | return self._button_immediate_function(type(self).button_install) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function odoo_1 | registry = modules.registry.Registry.new(self._cr.dbname, update_module=True) odoo_1 | File "", line 2, in new odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 87, in locked odoo_1 | return func(inst, *args, **kwargs) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new odoo_1 | odoo.modules.load_modules(registry, force_demo, status, update_module) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules odoo_1 | processed_modules += load_marked_modules(cr, graph, odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules odoo_1 | loaded, processed = load_module_graph( odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 231, in load_module_graph odoo_1 | load_data(cr, idref, mode, kind='data', package=package) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 71, in load_data odoo_1 | tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 763, in convert_file odoo_1 | convert_xml_import(cr, module, fp, idref, mode, noupdate) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 829, in convert_xml_import odoo_1 | obj.parse(doc.getroot()) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 749, in parse odoo_1 | self._tag_root(de) odoo_1 | File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 709, in _tag_root odoo_1 | raise ParseError(msg) from None # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback odoo_1 | odoo.tools.convert.ParseError: while parsing /opt/odoo/auto/addons/helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml:33 odoo_1 | Inherited view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition odoo_1 | odoo_1 | View error context: odoo_1 | '-no context-'

Corrected, I'm sorry, I was waiting for the dependency to be ready, I was missing a local commit.

**Comment by manuelcalerosolis** [comment]
@AntoniRomera functional review ok!

**Review by manuelcalerosolis — APPROVED** [review]
Functional review ok

**Comment by AntoniRomera** [comment]
@manuelcalerosolis Can you make another functional revision? The migration of the "project_timesheet_time_control" has changed the wizard.

**Review by FernandoRomera — APPROVED** [review]

**Pull request merged**
