### PR TITLE
Fix helpdesk_mgmt view

### PR DESCRIPTION
**Pull request by nguyenductamlhp**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is pushing whole 12.0 branch. Are you doing whole migration?

**Comment by emagdalenaC2i** [comment]
@nguyenductamlhp looks that is trying to merge in the wrong branch, 12.0 instead of 11.0

**Comment by nguyenductamlhp** [comment]
I rebased from lastest migration commit and fixed some errors on views

**Comment by pedrobaeza** [comment]
This is still pointing to 12.0 branch

**Comment by nguyenductamlhp** [comment]
I followed step by step on *Full process for beginners in Git flows* of [Migrate to version 12](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0). I made any mistake here?

**Comment by pedrobaeza** [comment]
If this is a migration to 12.0, why the PR title is "Fix helpdesk_mgmt view"?

**Comment by pedrobaeza** [comment]
I'm not seeing either your migration commit changing basic things like module version to `12.0.1.0.0`

**Comment by nguyenductamlhp** [comment]
So PR title should be *Migrate helpdesk_mgmt 11.0 to 12.0* ?

**Comment by pedrobaeza** [comment]
Well, strict format should be "[MIG] helpdesk_mgmt: Migration to 12.0", but the question is that this is not a valid migration, for things like the one I have said of the module version change. Check again https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration

**Comment by pedrobaeza** [comment]
#37 seems a legit migration, so closing

**Pull request closed without merging**
