### PR TITLE
[15.0] [IMP] helpdesk_mgmt adding kanban_state to form, tree and search views

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@eLBati can you rebase please ?

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by eLBati** [comment]
> @eLBati can you rebase please ?

Done

**Comment by marcelsavegnago** [comment]
ping @OCA/helpdesk-maintainers

**Review by dalonsod — APPROVED** [review]
Tested on runboat :+1: 

Kanban state field location in `form` view might be improved (e.g. project tasks or maintenance requests have that widget placed at sheet upper right square), but it's not important IMO

**Comment by flotho** [comment]
any chance to merge this one and forward ?

**Pull request closed without merging**
