### PR TITLE
[IMP] helpdesk_mgmt: Ticket creation from portal

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
See #75

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@pedrobaeza and @SamuelDomatix please review and approbe this PR

**Review by pedrobaeza — COMMENTED** [review]
Have you check how is the mail template seen in v12?

**Comment by emagdalenaC2i** [comment]
There are not mail templates in this PR

**Comment by pedrobaeza** [comment]
Sorry, my bad. I meant **QWeb** templates. In v12, now you have BS4 instead of BS3.

**Comment by emagdalenaC2i** [comment]
It looks good
image

**Review by pedrobaeza — APPROVED** [review]
code review

**Review by samuel-domatix — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
@pedrobaeza can you merge this PR?

**Comment by emagdalenaC2i** [comment]
@pedrobaeza it is usual than it takes more than 4 hours to merge this PR?

**Comment by pedrobaeza** [comment]
GitHub has been unstable this morning.

/ocabot merge minor

**Pull request closed without merging**
