### PR TITLE
[15.0][IMP] helpdesk_mgmt: Delete unused record 

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT44172

ping @pedrobaeza @victoralmau

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This is not a forward-port of 654a0d26aa91ae373bf9036ba0ffff16d74dda1b, so if the feature is already included, then the commit message should be different.

**Comment by CarlosRoca13** [comment]
Change done

**Comment by pedrobaeza** [comment]
Bump manually the manifest version and put the migration script in the new version. If not, it's not going to be executed for current installed modules.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
