### PR TITLE
[12.0] [ADD] helpdesk_mgmt_partner_sequence

### PR DESCRIPTION
**Pull request by lmiguens-solvos**
Provides different partner sequence in Helpdesk for ticket number generation.

### CODE REVIEW

**Comment by eLBati** [comment]
@lmiguens-solvos thanks. Please check travis

**Comment by lmiguens-solvos** [comment]
@eLBati, @dalonsod Can you review this PR?

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by dalonsod — APPROVED** [review]
👍

**Comment by eLBati** [comment]
LGTM
I would squash in 1 commit

**Comment by dalonsod** [comment]
hello @OCA/helpdesk-maintainers , is this PR ready to be merged? Thanks!

**Comment by dalonsod** [comment]
hello @OCA/helpdesk-maintainers , is it possible to merge this PR? Thanks!

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
