### PR TITLE
Backport to v10

### PR DESCRIPTION
**Pull request by mileo**
Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

### CODE REVIEW

**Comment by mileo** [comment]
Hi,

Dear repo's PSC should you create the 10.0 branch?

Best regards

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0, but switching 11.0/10.0 branches

**Comment by pedrobaeza** [comment]
Done: https://github.com/OCA/helpdesk/tree/10.0

**Comment by pedrobaeza** [comment]
Please retarget the branch and preserve commit history.

**Comment by gdgellatly** [comment]
@mileo This is targeting the wrong branch

**Pull request closed without merging**
