### PR TITLE
[13.0][FIX]helpdesk_mgmt_timesheet: default_project not a field helpdesk.ticket.team

### PR DESCRIPTION
**Pull request by manuelregidor**
default_project has to be replaced by default_project_id which is the right name of the field

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by HaraldPanten — APPROVED** [review]

**Comment by manuelregidor** [comment]
@ValentinVinagre

**Comment by HaraldPanten** [comment]
@DarioLodeiros

**Review by etobella — APPROVED** [review]

**Review by raistdev — APPROVED** [review]

**Comment by dalonsod** [comment]
@etobella this PR has not passed codecov. Is that correct anyway, or should be tests increased?

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
@simahawk could you have a quick look here?

**Pull request merged**
